name: flutter_application_6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  path: ^1.8.3
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.6.7
  firebase_messaging: ^14.7.17
  firebase_core: ^2.25.5
  google_sign_in: ^6.2.1

  
flutter_svg: ^2.0.10+1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets: 
   - assets/images/pullupimg.webp
   - assets/images/squats.webp
   - assets/images/setUp.jpeg
   - assets/images/jumping.png
   - assets/images/search.svg
   - assets/images/profile1.svg
   - assets/images/profile2.svg
   - assets/images/playicon.webp
   - assets/images/profile.svg
   - assets/images/timer.svg
   - assets/images/home.svg
   - assets/images/home1.svg
   - assets/images/info.svg
   - assets/images/info1.svg
   - assets/images/info2.svg
   - assets/images/pushup.jpg
   - assets/images/pullup.jpeg
  uses-material-design: true